INSERT INTO TBL_EMPLOYEES (first_name, last_name, email) VALUES
  ('Lokesh', 'Gupta', 'abc@gmail.com'),
  ('Deja1', 'Vu1', 'xyz@email.com'),
  ('Deja2', 'Vu2', 'xyz@email.com'),
  ('Deja3', 'Vu3', 'xyz@email.com'),
  ('Deja4', 'Vu4', 'xyz@email.com'),
  ('Deja5', 'Vu5', 'xyz@email.com'),
  ('Deja6', 'Vu6', 'xyz@email.com'),
  ('Deja7', 'Vu7', 'xyz@email.com'),
  ('Deja8', 'Vu8', 'xyz@email.com'),
  ('Deja9', 'Vu9', 'xyz@email.com'),
  ('Deja10', 'Vu10', 'xyz@email.com'),
  ('Deja11', 'Vu11', 'xyz@email.com'),
  ('Deja12', 'Vu12', 'xyz@email.com'),
  ('Deja13', 'Vu13', 'xyz@email.com'),
  ('Deja14', 'Vu14', 'xyz@email.com'),
  ('Caption', 'America', 'cap@marvel.com');