DROP TABLE IF EXISTS TBL_DEPT;
  
CREATE TABLE TBL_DEPT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  dept_id INT NOT NULL,
  dept_name VARCHAR(250) NOT NULL,
  stat CHAR(1) NOT NULL,
  created date NOT NULL,
  updated date NOT NULL
);
CREATE UNIQUE INDEX TBL_DEPT_DEPT_ID ON TBL_DEPT(
    dept_id
);
 

DROP TABLE IF EXISTS TBL_EMPLOYEES;

-- ALTER TABLE TBL_EMPLOYEES DROP CONSTRAINT FKob8ofh6kjhqdjpr47tupk9aj4;

  
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  dept_cd VARCHAR(20) NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  stat CHAR(1) NOT NULL,
  created date NOT NULL,
  updated date NOT NULL
);


  
